name: Rust CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 1.56.0
    - name: Build and Test
      run: cargo test

